bitrise-io/bitrise-workflow-editor

source/templates/code_signing.slim

Steps to replicate:
* Open the workflow editor
* Go to the code signing tab
* Scroll to the Generic File Storage section at the bottom
* Click ellipsis beside an existing file
* Click Delete
Expected result:
A popup confirming you want to delete the file
Actual result:
Nothing happens
This PR fixes a bug where the template is calling `deleteCertificate` on the `GenericFileController`, but that function doesn't exist. The function name appears to be `deleteGenericFile`.
Tested on prod by intercepting the response from bitrise and changing the function name, it allowed me to delete the file.

Fix issue where you can't delete a generic file

---

source/javascripts/controllers/_EnvVarsController.js.erb
source/javascripts/controllers/_MainController.js.erb
source/javascripts/services/_appService.js.erb

Changes:
- filtered empty key/value pairs from Environment variables list after save event triggered
- filtered empty key/value pairs from Secrets list after save event triggered

filtered empty key/value env vars and secrets

---

source/javascripts/controllers/_YMLController.js.erb

Change:
- Fixing YAML editor discard change to revert YAML to the saved version.

Discard button fix for yaml editor

---

webpack.config.js

uglify got deprecated -> migrated to terser but it drops comments be default.
This config is to preserve licence comments.

change terser config to preserve licence

---

_scripts/compile_api.sh
bitrise.yml
package.json

* `create-binaries` no longer have assets build dependency, it is handled explicitly on CI
* `setup-plugin-api` wf with assets build dependency 
`#plugin` tag would release plugin as well

[WEB-3520] plugin release #plugin

---

source/javascripts/services/_stepLibSearchService.ts

it caused failures for some orgs with very special workflow setup. I hotfixed it but we need to refactor step loading in the mid term.

[WEB-4246] ignore empty stepids

---

source/javascripts/controllers/_WorkflowsController.js.erb

Workflow rename throws an error if the workflow is used in a Stage.

[PLANG-289] Fix workflow rename

---

.tool-versions
package.json
source/javascripts/components/_AddStep.js.erb

https://bitrise.atlassian.net/browse/PLANG-556
NOTE: the root cause seem to be an Algolia filtering issue: I debugged the code, if a project type filter goes out to Algolia, it doesn't return any steps.
This fix does not fix the root cause but skips the Algolia filtering. Even though this results in larger traffic, this has been already what the users were doing to tackle the issue: clicking the All button to get all steps first and the filter locally. UX wise I don't see a noticable difference in load times and such.
Fixing the Algolia filtering requires more investigation/time and I suggest fixing this ASAP as it's a serious user facing issue.

[PLANG-556] Fix step list filtering

---

rails/strings.rb
source/javascripts/components/_AddStep.js.erb
source/stylesheets/_add_step_sidebar.scss.erb
source/templates/add_step_sidebar.slim

When searching for a step the default is Project Type filter which does not always return results
When this happens customers tend to think there are no steps available
This begs the question when we find no results should be show something to the user?
"We didn't find any results for your search in ReactNative steps, would you like to search all steps? <click link to search all steps>"
or 
"We didn't find any results for your search in ReactNative steps, here are some additional results we found that are not React"
Steps to reproduce:
Using a ReactNative app
In the WFE click + to add a new step
Search for "device testing for android"
Actual result:
No results are shown 
Expected result:
Results are shown

[PLANG-558] Add new step - search returns no results 

---

source/javascripts/components/StepItem/StepItemBadge.tsx

The deprecated icon doesn't have any size limits, so it's displayed as a 400x400px image.
The image is now constrained to 18px. This seems to be the size of other icons (in BitKit)

fix: deprecated icon size hotfix

---

source/javascripts/components/GuidedOnboarding/GuidedOnboardingAccordion.tsx

https://bitrise.atlassian.net/browse/PLG-380
Resolves an issue where content was passing underneath guide when in sticky header mode.

[PLG-380] bugfix for sticky header

---

source/javascripts/hooks/api/useFetchCallback.ts

Cloudflare will set a 4xx response if something is off and our error handling only checks for 5xx and if error_msg is present. I've added an additional constraint that we should check if the response is in 2xx range.

feat: set failed state if response isn't in 2xx range - CI-608

---

rails/strings.rb
source/javascripts/components/WorkflowMainToolbar/WorkflowMainToolbar.tsx
spec/integration/elements.js
spec/integration/workflows.feature
spec/integration/workflows/steps.js

Rename "Rearrange workflows" button to "Change Workflow execution order" to avoid customer confusion.

fix: Rename Rearrange workflows

---

source/javascripts/components/ProductTour/HighlighterProductTooltip.tsx

@avivenzio-bitrise I ran into issues with my previous branch and had to re-create my change on a new one. I also saw your comment regarding wanting to see screenshots. You were correct in that I had the wrong flex direction value. That has been updated, and everything else remains the same.

Made FE fixes to Product Tour

---

go.mod
go.sum

This PR pulls in an update data model from the CLI. The previous one was incorrect because the stage workflow did not have a `run_if` property. This meant that saving a yaml with the local workflow editor always removed this field.

[CI-2392] Update Bitrise data model

---

source/javascripts/controllers/_YMLController.js.erb

We often forget to upstream new additions/changes to the `bitrise.yml` schema because the workflow editor references the schema from our fork.
The upstream schema matches the fork as of yesterday: https://github.com/SchemaStore/schemastore/commit/7ad52d498e39b5237634bd6212fdf94f31457275

Use upstream schema

---

source/javascripts/controllers/_SecretsController.js.erb

The edit `forEach` that updates all Angular secrets based on their React counterparts didn't exclude the shared ones, so it messed up the original object with invalid prop overrides.

fix(secrets): fix editing on protected secret override

---

source/javascripts/components/StepConfigPanel/components/StepInput/StepInput.tsx

[CI-3106](https://bitrise.atlassian.net/browse/CI-3106)
The dropdown was wrapped in a `FormControl`. The chevron rotates when any `FormControl` parent is in an active state. So, when the `mousedown` event fires on the button, the top `FormControl` becomes active, causing the chevron to rotate.
Remove the dropdown from the `FormControl` because the `Dropdown` component has its own `FormControl` wrapper inside.
[CI-3106]: https://bitrise.atlassian.net/browse/CI-3106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: dropdown chevron is rotating on insert variable click

---

apiserver/service/bitrise_config.go
apiserver/tools/tools.go
go.mod
go.sum

This PR updates the Bitrise CLI dependency to the version [v2.16.1](https://github.com/bitrise-io/bitrise/releases/tag/2.16.1).
Other than a simply dep update `convertWorkflowElementTypes` had to be updated, because in the recent CLI version the Step List item isn't a homogenous list of Steps anymore, the item's are either Steps or the new With step groups.
The related CLI changes are here: https://github.com/bitrise-io/bitrise/pull/964
This is an example how the Bitrise CLI iterates on the steps of a workflow: https://github.com/bitrise-io/bitrise/blob/master/cli/run.go#L501-L533

Update bitrise dep to v2.16.1

---

go.mod
go.sum

This PR updates github.com/bitrise-io/bitrise to version [2.22.0](https://github.com/bitrise-io/bitrise/releases/tag/2.22.0), where a new `enabled` field was introduced for the target-based triggers.
I tested this change, by locally running the WFE and saving valid and invalid triggers.
A valid trigger saved without any validation error:
```
pipelines:
pl1:
triggers:
enabled: true
push:
- branch: master
```
while for invalid triggers WFE throws an error:
```
pipelines:
pl1:
triggers:
enabled: "should not be a string"
push:
- branch: master
```
error: `Validation failed: Config validation error: failed to get Bitrise config (bitrise.yml) from base 64 data: Failed to parse bitrise config, error: 'triggers': 'enabled' value should be a boolean`

Update github.com/bitrise-io/bitrise to version 2.22.0

---

bitrise.yml

The errcheck v1.8.0 causes unexpected errors on CI.

fix: errcheck version

---

source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.stories.tsx
source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.tsx
source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.types.ts
source/javascripts/components/unified-editor/WorkflowCard/components/ChainedWorkflowCard.tsx
source/javascripts/core/models/BitriseYmlService.spec.ts
source/javascripts/core/models/BitriseYmlService.ts
source/javascripts/core/stores/BitriseYmlStore.ts
source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.tsx
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/GraphEdge.tsx
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/Handles.tsx
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/WorkflowNode.tsx
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/autoLayoutingGraphNodes.ts
source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/createGraphEdge.ts
source/javascripts/pages/WorkflowsPage/components.new/WorkflowCanvasPanel/WorkflowCanvasPanel.tsx

- Fix workflow config panel, now opens chained workflows as well
- Implement remove chain workflow
- Implement remove pipeline workflow dependency
- Move node and edge deletion to the ReactFlow onNodesDelete and onEdgesDelete callbacks (to support Backspace deletion)

feat: Support deleting canvas nodes (depends_on items)

---

package-lock.json
package.json
source/javascripts/utils/withRootProvider.tsx

When an error occurs in React components, the whole WFE sometimes crashes, resulting in a blank screen for users. Additionally, no errors are logged in DataDog.
This PR addresses both issues: it prevents the blank screen while ensuring that errors are properly logged in DataDog, allowing the program to continue running without disruption.
https://docs.datadoghq.com/error_tracking/frontend/collecting_browser_errors/?tab=npm#react-error-boundaries-instrumentation

feat: log React rendering errors in DataDog

---

go.mod
go.sum

This PR updates github.com/bitrise-io/bitrise dep to v[2.27.1](https://github.com/bitrise-io/bitrise/releases/tag/2.27.1) to pull `title`, `summary`, and `description` properties for the Step bundle data models.

Update github.com/bitrise-io/bitrise dep to v2.27.1

---

go.mod
go.sum

This PR updates the `github.com/bitrise-io/bitrise` dependency to version [2.28.0](https://github.com/bitrise-io/bitrise/releases/tag/2.28.0).

Update github.com/bitrise-io/bitrise to version 2.28.0

---

source/javascripts/pages/SecretsPage/SecretsPage.tsx

Fix this kind of errors: https://app.datadoghq.com/rum/sessions?query=%40type%3Aerror%20service%3Awfe&agg_m=count&agg_m_source=base&agg_t=count&event=AwAAAZUjIElLRuSpaAAAABhBWlVqSUstc0FBQXVpYVlXZjVuS3pnQUEAAAAkMDE5NTIzMjQtM2NhNy00ZTI2LTg1ZTMtMGRmOGZkZWFjM2YwAAAEdQ&fromUser=false&refresh_mode=paused&viz=stream&from_ts=1740050325106&to_ts=1740052125106&live=true
The infinite loop was caused by `data: secrets = []`. With each state change, `secrets` was assigned a new array, causing the `useEffect` to run during every render cycle.

fix: infinite rendering loop on Secrets page

---

go.mod
go.sum

Update github.com/bitrise-io/bitrise/v2 version to [2.29.3](https://github.com/bitrise-io/bitrise/releases/tag/v2.29.3).

Update github.com/bitrise-io/bitrise/v2 to v2.29.3

---

source/javascripts/pages/EnvVarsPage/EnvVarsPage.tsx

**Problem:** After pressing 'Discard' having added (but not saved) a new EnvVar in the Workflows tab, I'm moved me to the bottom of the list in the Project tab - this is a bit confusing and annoying

fix: EnvVars page Tabs loose state on discard

---

source/javascripts/core/api/BitriseYmlApi.ts

Fix: https://bitrise.atlassian.net/servicedesk/customer/portal/30/SSW-2316

fix: improve YAML stringification for tabbed values

---

source/javascripts/hooks/useBitriseYmlStore.ts

JIRA Ticket: [CI-4997](https://bitrise.atlassian.net/browse/CI-4997)
Explanation: The `state.ymlDocument.toJSON()` method was called every time the `useBitriseYmlStore` hook was invoked. In this update, the JSON formatting is performed only once, and only when the `ymlDocument` changes.
[CI-4997]: https://bitrise.atlassian.net/browse/CI-4997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: graph pipeline performance issue

---

source/javascripts/core/stores/BitriseYmlStore.ts
source/javascripts/core/utils/YmlUtils.ts
source/javascripts/hooks/useYmlHasChanges.ts

Previously, the YAML document equality check was executed every time the document changed and whenever the `useYmlHasChanges` hook was used. Now, we store the `hasChanges` state and perform the calculation only once per change to improve efficiency.

perf: move some heavy operations into the store
