data/routes.yml, source/javascripts/services/_requestService.js.erb, source/javascripts/services/_stepSourceService.js.erb
steps specified by git URL - implemented;
steps specified by local path - implemented
=> git step, local step handling implemented

data/routes.yml, source/index.slim, source/javascripts/components/_AddStep.js.erb, source/javascripts/components/_Trigger.js.erb, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/services/_appService.js.erb, source/javascripts/services/_iframeService.js.erb, source/javascripts/services/_requestService.js.erb, source/stylesheets/_add_step_sidebar.scss.erb, source/stylesheets/_tab-code_signing.scss.erb, source/stylesheets/_tab-workflows.scss.erb, source/stylesheets/main.scss, source/templates/add_step_sidebar.slim, source/templates/code_signing.slim, source/templates/workflows.slim
- empty workflows handled
- Devcenter URL fix
- pull request triggers only need source or target branch pattern
- inputs-outputs fix for steps without inputs or outputs
=> quickfixes

data/strings.yml, source/stylesheets/_tab-workflows.scss.erb
=> Environment Variables will be replaced in input... - clarification

source/templates/workflows.slim
=> show input description when the input field is expanded

source/_javascripts.slim, source/javascripts/main.js, source/javascripts/vendor.js
- new CDN link for jQuery
- separate merged .js file for non-changing scripts
=> CDN updates

source/javascripts/controllers/_EnvVarsController.js.erb
But without changing it being `true` as the default value.
=> Make env vars “is expand” false on create

source/templates/code_signing.slim
Will try other methods later if this does not work out.
=> Password field fix - method #1

data/strings.yml
Changes:
- remove secret tabs wrong text from warning box
=> Secrets - Remove text fix #4et1a

data/strings.yml, source/templates/secrets.slim
Changes:
- Fixed secrets tab variables listing page layout alignment issue.
CBT:
https://app.crossbrowsertesting.com/public/i3cc64c79932d1e3/screenshots/z905e30e94ab106529fc
=> Fixing secrets tab alignment #4etqg

data/strings.yml, source/stylesheets/_constants.scss, source/stylesheets/_tab-code_signing.scss.erb, source/templates/code_signing.slim
Change:
- Updated codesign tab generic file store section UI.
=> Update: Codesign tab generic filestore section #3azrw

source/index.slim, source/javascripts/components/_stickyHeader.js, source/javascripts/controllers/_MainController.js.erb, source/stylesheets/_index.scss.erb, source/stylesheets/main.scss
This reverts commit f375daf43bda1a48dcd5ad0c4b1d73dbd7a1c27a.
=> Revert "Safari scrolling issue fix (#316)"

source/index.slim, source/stylesheets/_add_step_sidebar.scss.erb, source/stylesheets/_constants.scss, source/stylesheets/_popup.scss.erb, source/stylesheets/_rebo.scss, source/stylesheets/_tab-triggers.scss.erb, source/stylesheets/_tab-workflows.scss.erb, source/templates/code_signing.slim, source/templates/env_vars.slim, source/templates/secrets.slim, source/templates/triggers.slim, source/templates/workflows.slim, source/templates/yml.slim
This reverts commit 73fed5c8508cff75ce8bb12d8e1a0cf2c9e08c84.
=> Revert "Update green backgrounded selectables to purple (#344)"

source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim
=> Fix rename workflow checkmark background

apiserver/service/bitrise_config.go, apiserver/service/bitrise_config_test.go, apiserver/service/bitrise_secrets.go, apiserver/service/bitrise_secrets_test.go, apiserver/utility/utility.go, apiserver/utility/utility_test.go, source/javascripts/services/_appService.js.erb
Saving bitrise.yml: display warnings to the user that was given by the CLI
ClickUp card link: https://app.clickup.com/t/a3k79
TODO before release:
=> Saving bitrise.yml: display warnings #a3k79

README.md, source/javascripts/filters/_versionFilters.js.erb, source/javascripts/main.js, source/javascripts/services/_semverService.js.erb, source/templates/workflows.slim, spec/javascripts/filters/versionFilter.spec.js, spec/javascripts/semverService.spec.js
Reverts bitrise-io/bitrise-workflow-editor#416
=> Revert "[WEB-3337] disable non wildcard versions in version selector"

README.md, docker-compose.yml, package.json, source/javascripts/controllers/_MainController.js.erb, spec/karma.conf.js
* picked up some common change from version branch
* updated readme
* exposed livereload port from docker
=> [WEB-3482] release

CHANGELOG.md, bitrise-plugin.yml, bitrise.yml, version/version.go
This reverts commit e786e6fbcb08cb175a894f938e9a9d530b7623c4.
=> Revert "version bump (1.1.72 -> 1.1.73) (#433)"

source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/services/_stepSourceService.js.erb, source/stylesheets/_constants.scss, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim, webpack.config.js
* `ng-init` only run once so selected step wasn't updated -> had to revert back to use selected step
* change `font-url` to `url`, webpack didn't load the font properly
* safety check for $digest cycle
=> master deploy fixes

source/stylesheets/_tab-workflows.scss.erb
=> Fix flex bug [WEB-3242]

source/stylesheets/_tab-env_vars.scss.erb, source/stylesheets/_tab-secrets.scss.erb, source/stylesheets/_tab-yml.scss
=> Fix stylesheets referencing image URLs

package-lock.json, package.json
This update should fix the inputs not showing up when selecting a step.
=> Bump steplib search version

source/javascripts/controllers/_WorkflowsController.js.erb
=> [EN-243] Fix step delete issue

source/javascripts/components/_Trigger.js.erb, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_TriggersController.js.erb, source/templates/triggers.slim, spec/javascripts/components/Trigger.spec.js
=> [EN-331] Add pipelines to trigger target dropdown

source/javascripts/controllers/_WorkflowsController.js.erb, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim, spec/integration/common.js, spec/integration/elements.js, spec/integration/workflows-steps-details.feature, spec/integration/workflows-steps-inputs.feature, spec/integration/workflows.feature
=> Enable separate scrolling of blocks

package-lock.json, package.json
Closes #579 
https://bitrise.atlassian.net/browse/PLANG-919
=> chore(npm): update underscore

source/javascripts/controllers/_StackController.js.erb, spec/integration/workflows-steps-details.feature
https://user-images.githubusercontent.com/97228168/150814266-ddc958ce-cfc4-4e17-8ff8-1955fd4b1fcf.mp4
=> [PLANG-715] Keep selected machine type while switching between stacks

source/javascripts/_componentRegister.js, source/javascripts/components/workflow-recipes/WorkflowRecipesInfoBanner/WorkflowRecipesInfoBanner.tsx, source/templates/add_step_sidebar.slim
https://bitrise.atlassian.net/browse/OX-579
=> feat: Display new workflow recipe info banner on step sidebar [OX-579] 

bitrise.yml, rails/strings.rb, source/javascripts/components/_Stack.js, source/javascripts/controllers/_StackController.js.erb, source/javascripts/services/_requestService.js.erb, source/stylesheets/_tab-stack.scss.erb, source/templates/stack.slim
https://bitrise.atlassian.net/browse/PLANG-1539
The new look with 2 links:
The old look for 1 link (did not change):
=> [PLANG-1539] Support Apple Silicon's system reports on the Stacks & Machines page

package-lock.json, package.json, rails/strings.rb, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_TriggersController.js.erb, source/javascripts/services/_appService.js.erb, source/javascripts/services/_launchDarklyService.js.erb, source/javascripts/services/_requestService.js.erb
JIRA ticket: https://bitrise.atlassian.net/browse/PLANG-1053
=> [PLANG-1053] Use feature flag instead of beta tag to display pipelines on triggers page

source/javascripts/components/_Variable.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim
https://bitrise.atlassian.net/browse/SWAT-15
=> Fix short description toggle for steps [SWAT-15]

rails/strings.rb
https://bitrise.atlassian.net/browse/SWAT-90
=> Fix get team-test-devices url [SWAT-90]

source/javascripts/controllers/_YMLController.js.erb
https://bitrise.atlassian.net/browse/PLANG-2221
=> fix: YML editor is broken when navigating back from another tab 

_scripts/compile_api.sh, bitrise.yml, package.json, source/javascripts/_componentRegister.js, source/javascripts/components/ProductTour/Highlighter.scss, source/javascripts/components/ProductTour/Highlighter.tsx, source/javascripts/components/ProductTour/Portal.scss, source/javascripts/components/ProductTour/Portal.tsx, source/javascripts/components/ProductTour/ProductTooltip.scss, source/javascripts/components/ProductTour/ProductTooltip.tsx, source/javascripts/components/ProductTour/ProductTour.tsx, source/javascripts/components/ProductTour/tips.ts, source/javascripts/components/ProductTour/types.ts, source/javascripts/components/ProductTour/useHighlightedArea.ts, source/javascripts/components/ProductTour/useProductTour.ts, source/javascripts/components/ProductTour/useTrackingFunction.ts, source/javascripts/components/ProductTour/useWaitForElement.ts, source/javascripts/controllers/_MainController.js.erb, source/javascripts/services/_requestService.js.erb, source/templates/_main.slim, spec/integration/workflows-steps-details.feature, webpack.config.js
JIRA Link: https://bitrise.atlassian.net/browse/PLG-226
=> PLG-226 - WFE Product tour

rails/strings.rb, source/javascripts/controllers/_StackController.js.erb, source/templates/stack.slim
Jira: https://bitrise.atlassian.net/browse/PLG-295
Add beta warning for M1 Max Elite XL machines.
=> add beta warning for m1 max elite xl machines

source/javascripts/controllers/_StackController.js.erb, source/templates/stack.slim
JIRA ticket: https://bitrise.atlassian.net/browse/SWAT-716
=> Fix stack description url [SWAT-716]

spec/integration/common.js, spec/integration/elements.js, spec/integration/workflows-steps-details.feature
https://bitrise.atlassian.net/browse/FRONTEND-192
Steps load slower, possibly related to rendering changes in react18 causing cypress to click on nothing.
=> Try to improve test flakyness [FRONTEND-192]

source/javascripts/components/UpdateYmlInRepositoryModal/UpdateYmlInRepositoryModal.tsx, source/javascripts/components/YmlStorageSettings/ConfirmSwitchToRepositoryYml.tsx
https://bitrise.atlassian.net/browse/FRONTEND-195
=> Bitkit migration - fix modal footer [FRONTEND-195]

package-lock.json, package.json, source/javascripts/components/GuidedOnboarding/GuidedOnboardingAccordion.tsx, source/javascripts/components/GuidedOnboarding/Steps.tsx, spec/integration/workflows-steps-details.feature
https://bitrise.atlassian.net/browse/FRONTEND-207
- upgrade bitkit to remove hacky solution to issue with sticky header spacing
- upgrade also results in updated step icons which will improve consistency on getting started guide between website and WFE
=> [FRONTEND-207] bitkit update accordion fix

source/javascripts/_componentRegister.js, source/javascripts/components/GuidedOnboarding/GuidedOnboarding.tsx, source/javascripts/components/GuidedOnboarding/types.ts, source/javascripts/services/_requestService.js.erb, source/templates/_main.slim
https://bitrise.atlassian.net/browse/PLG-377
- change build icon on guide based on build status
=> [PLG-377] update guide build icon based on build status

source/stylesheets/_index.scss.erb, source/templates/_main.slim, spec/integration/common.js, spec/integration/workflows-steps-details.feature
=> Change main content CSS class to avoid collision with monaco editor hintbox

source/javascripts/controllers/_WorkflowsController.js.erb, source/templates/workflows.slim
https://user-images.githubusercontent.com/8428264/202181838-ca3b660b-3d7f-416f-b0c8-1825ef5601da.mov
=> Step input insert variable fix [SWAT-963]

rails/strings.rb, source/javascripts/_serviceRegister.js, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_StackController.js.erb, source/javascripts/services/_appService.js.erb, source/javascripts/services/_requestService.js.erb, source/javascripts/services/plan-service.ts, source/templates/stack.slim
https://bitrise.atlassian.net/browse/PLG-947
Hide credits on machine types for starter package users.
=> [PLG-947] hide machine credits for starter package

source/javascripts/controllers/_MainController.js.erb
Remove onboarding guide feature flag.
Task - https://bitrise.atlassian.net/browse/PLG-386
Subtask - https://bitrise.atlassian.net/browse/PLG-1006
=> [PLG-1006] remove onboarding guide feature flag

source/javascripts/components/WorkflowSelector/WorkflowSelector.tsx
Close [CI-908](https://bitrise.atlassian.net/browse/CI-908)
[CI-908]: https://bitrise.atlassian.net/browse/CI-908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Remove fix workflow width #plugin

_scripts/set_version.go, bitrise-plugin.yml
Close [CI-571](https://bitrise.atlassian.net/browse/CI-571)
[CI-571]: https://bitrise.atlassian.net/browse/CI-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Fix plugin version updater and plugin version

bitrise-plugin.yml, package-lock.json, package.json, version/version.go
This version number will be the next release's version number
=> Bump version number

rails/strings.rb, source/javascripts/controllers/_StackController.js.erb, source/stylesheets/_tab-stack.scss.erb, source/templates/stack.slim
https://bitrise.atlassian.net/browse/PLG-1204
Hold deployment until the entire story is ready - 
https://bitrise.atlassian.net/browse/PLG-1194
=> [PLG-1204] remove machine beta warnings from stacks tab

rails/strings.rb, source/javascripts/controllers/_StackController.js.erb, source/stylesheets/_tab-stack.scss.erb, source/templates/stack.slim
Reverts bitrise-io/bitrise-workflow-editor#744
=> Revert "[PLG-1204] remove machine beta warnings from stacks tab"

source/javascripts/controllers/_StackController.js.erb, source/templates/stack.slim
https://bitrise.atlassian.net/browse/PLG-1289
=> [PLG-1289] group machine types by chip

source/javascripts/services/_appService.js.erb
https://bitrise.atlassian.net/browse/SSW-120
=> [SSW-120] return copy of all stacks for other project type

source/javascripts/controllers/_MainController.js.erb
=> Fix invalid stack UI logic [SSW-151]

source/javascripts/controllers/_MainController.js.erb
https://bitrise.atlassian.net/browse/PLG-1516
https://bitrise.atlassian.net/browse/PLG-1517
=> [PLG-1500] hide product tour behind a feature flag

source/javascripts/_componentRegister.js, source/javascripts/components/ProductTour/ProductTour.tsx, source/javascripts/components/ProductTour/types.ts, source/javascripts/controllers/_MainController.js.erb, source/templates/_main.slim
https://bitrise.atlassian.net/browse/PLG-1524
=> [PLG-1524] remove guide auto-open code

source/javascripts/components/ProductTour/tips.ts, source/javascripts/components/WorkflowMainToolbar/WorkflowMainToolbar.tsx
https://bitrise.atlassian.net/browse/PLG-1561
This change introduced the issue - https://github.com/bitrise-io/bitrise-workflow-editor/pull/758/files#diff-c9aceac0c0578d5a6e5592f0c3e24099caebe8a5a16708e39914ec308f168408L25
=> [PLG-1561] fix product tour step 2 rendering

bitrise.yml
Same fix as in the website repo:
https://github.com/bitrise-io/bitrise-website/pull/9822
=> ci: Fix "install nodejs with asdf" step

source/javascripts/_BitriseWorkflowEditor.js.erb, source/javascripts/services/_appService.js.erb
Closes [CI-1407](https://bitrise.atlassian.net/browse/CI-1407)
[CI-1407]: https://bitrise.atlassian.net/browse/CI-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Track "WFE - YML changes saved" event

source/javascripts/services/plan-service.ts
https://bitrise.atlassian.net/browse/PLG-1967
=> [PLG-1967] add deprecated plans to modern concurrency

source/javascripts/controllers/_GenericFileController.js.erb
https://bitrise.atlassian.net/browse/CI-444
=> Increase max generic files count to 50 [CI-444]

source/javascripts/components/_Stack.js, source/javascripts/components/_Workflow.js.erb, source/javascripts/controllers/_StackController.js.erb, source/javascripts/services/_appService.js.erb, source/javascripts/services/_requestService.js.erb, source/templates/stack.slim
Don't save the machine type id to bitrise.yml when the selected stack is an agent pool type. 
https://bitfall.slack.com/archives/C056QA26KR8/p1684425953078149
=> CI-1570-poc-fe-fixes

rails/strings.rb, source/javascripts/controllers/_MainController.js.erb, source/templates/_main.slim
JIRA: https://bitrise.atlassian.net/browse/BIVS-2034
=> feat: add workflows and pipelines breadcrumb

rails/strings.rb, source/javascripts/services/_appService.js.erb
there was an issue with `undefined !== null` when checking for missing value, the fix is using `!=` instead.
=> fix: small WFE bugs [BIVS-2050]

bitrise.yml
Try to solve:
https://app.bitrise.io/build/ea7cf65f-8793-4f22-8e98-11f3d8519876
=> [RA-2047] Move on when the nodejs plugin is already added to asdf

source/javascripts/controllers/_WorkflowsController.js.erb
https://bitrise.atlassian.net/browse/BIVS-2319
=> Fix add workflow parameter handler

package-lock.json, source/stylesheets/_tab-triggers.scss.erb, source/templates/triggers.slim
https://bitrise.atlassian.net/browse/BIVS-2367
=> Update draft pr label text

source/javascripts/components/YmlStorageSettings/YmlStorageSettings.tsx, source/stylesheets/_tab-licenses.scss.erb
=> fix: link colors on Licenses & bitrise.yml pages

package-lock.json, package.json, tsconfig.json
=> chore: update Bitkit to latest

source/javascripts/_componentRegister.js, source/javascripts/components/StepConfig.tsx, source/javascripts/components/StepOutputVariables.tsx, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/models.ts, source/templates/workflows.slim
=> feat: Implement Output variables tab

source/javascripts/_componentRegister.js, source/javascripts/components/SecretsDialog/SecretsDialog.stories.tsx, source/javascripts/components/SecretsDialog/SecretsDialog.tsx, source/javascripts/components/SecretsDialog/SecretsDialogProvider.stories.tsx, source/javascripts/components/SecretsDialog/SecretsDialogProvider.tsx, source/javascripts/components/SecretsDialog/components/CreateSecret.tsx, source/javascripts/components/SecretsDialog/components/SecretsTable.tsx, source/javascripts/components/SecretsDialog/components/SecretsTableRow.tsx, source/javascripts/components/SecretsDialog/index.ts, source/javascripts/components/SecretsDialog/types.ts, source/javascripts/components/StepConfig.tsx, source/javascripts/components/StepConfiguration/components/StepInput/StepInput.tsx, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/templates/workflows.slim
https://github.com/bitrise-io/bitrise-workflow-editor/assets/1190738/51cc40e2-359b-436a-9143-7c7cf0fb43f1
=> feat: implement secrets dialog

source/templates/stack.slim
=> [SSW-1335] There is no border around Stack selector dropdown

source/javascripts/_componentRegister.js, source/javascripts/components/StepVersionDetails/StepVersionDetails.tsx, source/javascripts/components/_Step.js, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/models.ts, source/javascripts/services/semver-service.ts, source/templates/workflows.slim
- Version update
- Version texts
- Step deletion from utility workflow
=> fix: step related regressions

package-lock.json, source/javascripts/_componentRegister.js, source/javascripts/components/EnvironmentVariablesDialog/EnvironmentVariablesDialog.stories.tsx, source/javascripts/components/EnvironmentVariablesDialog/EnvironmentVariablesDialog.tsx, source/javascripts/components/EnvironmentVariablesDialog/EnvironmentVariablesDialogProvider.stories.tsx, source/javascripts/components/EnvironmentVariablesDialog/EnvironmentVariablesDialogProvider.tsx, source/javascripts/components/EnvironmentVariablesDialog/components/EnvironmentVariablesTable.tsx, source/javascripts/components/EnvironmentVariablesDialog/components/EnvironmentVariablesTableRow.tsx, source/javascripts/components/EnvironmentVariablesDialog/types.ts, source/javascripts/components/SecretsDialog/SecretsDialogProvider.tsx, source/javascripts/components/SecretsDialog/components/SecretsTable.tsx, source/javascripts/components/SecretsDialog/components/SecretsTableRow.tsx, source/javascripts/components/StepConfig.tsx, source/javascripts/components/StepConfiguration/components/StepInput/StepInput.tsx, source/javascripts/controllers/_InsertVariableController.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim
=> feat: environment variables dialog

source/javascripts/components/StepConfiguration/StepConfiguration.tsx, source/javascripts/components/StepConfiguration/components/StepInputList.tsx
JIRA task: https://bitrise.atlassian.net/browse/CI-2845
=> feat: validation error counter for step input categories

source/javascripts/components/TriggersPage/TriggersPage.tsx, source/javascripts/hooks/api/useGetUserMetaData.ts, source/javascripts/hooks/api/usePutUserMetaData.ts
https://bitrise.atlassian.net/browse/BIVS-2528
=> Triggers page: Save notification close to user metadata [BIVS-2528]

.tool-versions, package-lock.json, package.json, renovate.json, source/javascripts/components/StepConfiguration/components/StepInput/StepInput.tsx
https://bitrise.atlassian.net/browse/CI-2880
=> [CI-2880] Display environment variable as a select option when it has been set in the bitrise.yml

source/javascripts/_componentRegister.js, source/javascripts/components/WorkflowEmptyState/WorkflowEmptyState.tsx, source/javascripts/components/WorkflowMainToolbar/WorkflowMainToolbar.tsx, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/services/workflows-selection-service.ts, source/templates/workflows.slim
=> fix: deleting the last workflow

source/javascripts/components/StepConfig.tsx, source/javascripts/components/StepProperties/StepProperties.tsx, source/javascripts/controllers/_WorkflowsController.js.erb, spec/integration/elements.js
=> fix: flutter version should not update the step version

source/javascripts/components/YmlStorageSettings/StoreInRepository.tsx
You can try with the `?version=2.0.6072-beta` url parameter.
=> fix: missing yml storage change confirmation

source/javascripts/controllers/_WorkflowsController.js.erb
JIRA ticket: https://bitrise.atlassian.net/browse/CI-2864
=> fix: ensure inputs do not lose focus on first change

source/javascripts/controllers/_StackController.js.erb
https://bitrise.atlassian.net/browse/BIVS-2306
=> Hide utility workflows from the stacks and machines page [BIVS-2306]

source/javascripts/components/TriggersPage/AddPrTriggerDialog.tsx, source/javascripts/components/TriggersPage/AddPushTriggerDialog.tsx, source/javascripts/components/TriggersPage/AddTagTriggerDialog.tsx
JIRA Card: https://bitrise.atlassian.net/browse/BIVS-2578
=> [BIVS-2578] Fix dropdowns in trigger dialogs

source/javascripts/components/StepConfiguration/components/StepInput/StepInput.tsx, source/stylesheets/_tab-workflows.scss.erb
https://bitrise.atlassian.net/browse/CI-2885
=> fix: step config panel is too small on smaller screens

source/javascripts/components/StepItem/StepItem.tsx
=> fix: remove step item tooltip

source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/services/_requestService.js.erb
Related JIRA tickets:
- https://bitrise.atlassian.net/browse/CI-2785
- https://bitrise.atlassian.net/browse/CI-2786
- https://bitrise.atlassian.net/browse/CI-2787
=> chore: remove unused feature flags

package-lock.json, package.json, source/javascripts/components/PipelinesPage/PipelinesPage.stories.tsx, source/javascripts/components/PipelinesPage/PipelinesPage.tsx, source/javascripts/components/PipelinesPage/components/PipelinesCanvas.tsx, source/stylesheets/_index.scss.erb
[CI-3059](https://bitrise.atlassian.net/browse/CI-3059)
[CI-3060](https://bitrise.atlassian.net/browse/CI-3060)
[CI-3059]: https://bitrise.atlassian.net/browse/CI-3059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CI-3060]: https://bitrise.atlassian.net/browse/CI-3060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add react-flow package and create PipelineCanvas component

source/javascripts/components/SecretsPage/SecretsPage.tsx
https://bitrise.atlassian.net/browse/ER-1375
=> fix minor bugs in SecretsPage [ER-1375]

source/javascripts/components/SecretsPage/SecretCard.tsx
https://bitrise.atlassian.net/browse/ER-1342
=> fix clicking on shared badge deleting app secret [ER-1342]

source/javascripts/components/PipelinesPage/PipelinesPage.tsx, source/javascripts/components/PipelinesPage/PipelinesPage.types.ts, source/javascripts/components/PipelinesPage/components/StageNode.tsx, source/javascripts/components/PipelinesPage/components/WorkflowCard/StepCard.tsx, source/javascripts/components/PipelinesPage/components/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/PipelinesPage/hooks/useMeta.ts, source/javascripts/components/PipelinesPage/hooks/useWorkflow.ts, spec/integration/test_bitrise.yml
=> feat: display workflow in the stage node on the canvas

source/javascripts/_componentRegister.js, source/javascripts/components/PipelinesPage/PipelinesPage.tsx, source/javascripts/components/PipelinesPage/components/PipelinesCanvas.tsx, source/javascripts/components/PipelinesPage/components/StageNode.tsx, source/javascripts/components/PipelinesPage/components/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/PipelinesPage/hooks/useMeta.ts, source/javascripts/components/PipelinesPage/hooks/useWorkflowChain.ts, source/javascripts/components/PipelinesPage/providers/BitriseYmlProvider.tsx, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_PipelinesController.js.erb, source/templates/pipelines.slim
[CI-2949](https://bitrise.atlassian.net/browse/CI-2949)
[CI-2949]: https://bitrise.atlassian.net/browse/CI-2949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: display chained workflows in pipeline viewer

package-lock.json, package.json, source/javascripts/components/StepConfigPanel/components/StepHelperText.tsx
=> Fix MarkdownContent component: Use inline code snippet instead of a multiline

source/javascripts/components/PipelinesPage/PipelinesPage.tsx, source/javascripts/components/PipelinesPage/components/PipelinesCanvas.tsx, source/javascripts/components/PipelinesPage/components/PipelinesEmptyState.tsx, source/javascripts/components/PipelinesPage/components/PipelinesHeader.tsx, source/javascripts/components/PipelinesPage/components/StageNode.tsx, source/javascripts/components/PipelinesPage/components/StepCard.tsx, source/javascripts/components/PipelinesPage/components/WorkflowCard.stories.tsx, source/javascripts/components/PipelinesPage/components/WorkflowCard.tsx
https://bitrise.atlassian.net/browse/CI-3124
=> feat: Implement empty state for the pipeline viewer

source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_SecretsController.js.erb, source/javascripts/services/_appService.js.erb
https://bitrise.atlassian.net/browse/ER-1400
=> do not use the old endpoint for saving secrets [ER-1400]

source/javascripts/controllers/_MainController.js.erb
[CI-3136](https://bitrise.atlassian.net/browse/CI-3136)
LaunchDarkly: https://app.launchdarkly.com/projects/website/flags/enable-new-wfe-workflow-config-panel/targeting?env=production&env=test&env=development&selected-env=production
[CI-3136]: https://bitrise.atlassian.net/browse/CI-3136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: new workflow config panel LD flag

source/javascripts/components/SecretsPage/SecretCard.tsx
https://bitrise.atlassian.net/browse/ER-1371
=> fix readonly input styles in SecretCard [ER-1371]

source/javascripts/components/SecretsPage/SecretCard.tsx
https://bitrise.atlassian.net/browse/SSW-1558
=> fix multiline secret editability [SSW-1558]

source/javascripts/_BitriseWorkflowEditor.js.erb, source/javascripts/_componentRegister.js, source/javascripts/components/StepConfigPanel/StepConfigPanel.tsx, source/javascripts/controllers/_WorkflowsController.js.erb, source/templates/workflows.slim
https://bitrise.atlassian.net/browse/ER-1417
=> use new endpoints when creating a secret from step config UI [ER-1417]

source/javascripts/components/SecretsPage/SecretCard.tsx, source/javascripts/components/StepConfigPanel/StepConfigPanel.tsx
=> Fix typo in Secret field [ER-1411]

source/javascripts/controllers/_CreateAndInsertSecretVariableController.js.erb, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_SecretsController.js.erb
https://bitrise.atlassian.net/browse/ER-1417
=> skip old endpoint save in every case [ER-1417]

source/javascripts/components/WorkflowConfigPanel/WorkflowConfigPanel.types.ts, source/javascripts/components/WorkflowConfigPanel/components/StackAndMachineCard.tsx, source/javascripts/components/WorkflowConfigPanel/hooks/useStackAndMachine.ts, source/javascripts/controllers/_WorkflowsController.js.erb
[CI-3162](https://bitrise.atlassian.net/browse/CI-3162)
[CI-3162]: https://bitrise.atlassian.net/browse/CI-3162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: handle dedicated machine type on the new workflow config panel

source/javascripts/components/WorkflowConfigPanel/WorkflowConfigPanel.mswMocks.ts, source/javascripts/components/WorkflowConfigPanel/WorkflowConfigPanel.stories.tsx, source/javascripts/components/WorkflowConfigPanel/components/StackAndMachineCard.tsx, source/javascripts/components/WorkflowConfigPanel/hooks/useStackAndMachine.ts, source/javascripts/components/WorkflowConfigPanel/services/getAllStackInfo.ts
[CI-3164](https://bitrise.atlassian.net/browse/CI-3164)
[CI-3164]: https://bitrise.atlassian.net/browse/CI-3164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: handle self-hosted runner on new workflow config panel

source/javascripts/controllers/_MainController.js.erb
closes [CI-3222](https://bitrise.atlassian.net/browse/CI-3222)
[CI-3222]: https://bitrise.atlassian.net/browse/CI-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: browser url is not updating on tab change

source/javascripts/components/StepBadge/StepBadge.tsx, source/javascripts/components/StepDrawer/StepDrawer.tsx, source/javascripts/components/StepDrawer/StepDrawer.types.ts, source/javascripts/components/StepDrawer/StepDrawer.utils.ts, source/javascripts/components/StepDrawer/components/DrawerStepCard.tsx, source/javascripts/components/StepDrawer/components/StepList.tsx, source/javascripts/components/StepDrawer/hooks/useDebouncedFormValues.ts, source/javascripts/components/StepDrawer/hooks/useVirtualizedItems.ts
- Change "verified" badge label
- Show summary or first line of description
- Don't show category names when a search term is provided
=> fix: Additional StepDrawer improvements

source/javascripts/components/StepBadge/StepBadge.tsx, source/javascripts/components/StepDrawer/StepDrawer.types.ts, source/javascripts/components/StepDrawer/StepDrawer.utils.ts, source/javascripts/components/StepDrawer/hooks/StepDrawer.mswMocks.ts, source/javascripts/models/Algolia.ts
Closes: https://bitrise.atlassian.net/browse/CI-3270
=> hotfix: verified step

source/javascripts/datadog-rum.js.erb
This reverts commit d085b89d93f98ded1dce918d4f8a089c0db4478f.
=> Revert "make datadog config similar to website (#1072)"

source/javascripts/controllers/_MainController.js.erb, source/javascripts/pages/WorkflowsPage/components/WorkflowMainToolbar/WorkflowMainToolbar.tsx, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim
https://bitrise.atlassian.net/browse/CI-3298
=> feat: move workflow toolbar to steps container

rails/strings.rb, source/javascripts/_componentRegister.js, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/pages/WorkflowsPage/components/CreateWorkflowDialog/CreateWorkflowDialog.tsx, source/stylesheets/_tab-workflows.scss.erb, source/templates/workflows.slim
https://bitrise.atlassian.net/browse/CI-3331
=> feat: connect the new create wf dialog

source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/models/EnvVar.ts, source/javascripts/pages/WorkflowsPage/components/WorkflowConfigPanel/components/EnvVarsCard.tsx
https://bitrise.atlassian.net/browse/CI-3337
=> fix: wrong boolean and number values in wf config envs ui

rails/strings.rb, source/javascripts/components/ConfigurationYmlSource/ConfigurationYmlSourceDialog.tsx, source/javascripts/components/UpdateConfigurationDialog/UpdateConfigurationDialog.tsx, source/javascripts/pages/SecretsPage/SecretsPage.tsx
https://bitrise.atlassian.net/browse/ER-1401
=> rename app to project [ER-1401]

source/javascripts/components/StepItem/StepItem.tsx, source/javascripts/components/_Step.js, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/pages/WorkflowsPage/components/WithBlockPanel/WithBlockPanel.tsx, source/javascripts/services/_appService.js.erb, source/templates/workflows.slim
[x] JIRA card: https://bitrise.atlassian.net/browse/BIVS-2751
=> [BIVS-2751] Step bundles small fixes

source/javascripts/components/ConfigurationYmlSource/ConfigurationYmlSourceDialog.tsx, source/javascripts/components/UpdateConfigurationDialog/UpdateConfigurationDialog.tsx, source/javascripts/components/YmlEditorHeader/YmlEditorHeader.tsx
[X] JIRA card: https://bitrise.atlassian.net/browse/BIVS-2703
=> [BIVS-2703] Modular yaml event tracking

source/javascripts/components/StepItem/StepItem.tsx, source/templates/workflows.slim
https://bitrise.atlassian.net/browse/CI-3432
=> fix: step title out of sync on rename

package-lock.json, source/javascripts/components/WorkflowCard/WorkflowCard.tsx, source/javascripts/pages/WorkflowsPage/WorkflowsPage.store.ts, source/javascripts/pages/WorkflowsPage/WorkflowsPage.tsx, source/javascripts/pages/WorkflowsPage/components.new/WorkflowCanvasPanel/WorkflowCanvasPanel.tsx
https://bitrise.atlassian.net/browse/CI-3410
=> feat: edit workflow button for workflow card

source/javascripts/components/StepCard/StepCard.tsx, source/javascripts/components/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/WorkflowCard/WorkflowCard.utils.ts, source/javascripts/contexts/BitriseYmlProvider.tsx, source/javascripts/models/BitriseYmlService.spec.ts, source/javascripts/models/BitriseYmlService.ts, source/javascripts/pages/WorkflowsPage/components.new/WorkflowCanvasPanel/WorkflowCanvasPanel.tsx
https://bitrise.atlassian.net/browse/CI-2747
https://bitrise.atlassian.net/browse/CI-3413
https://github.com/user-attachments/assets/b9d64204-3f41-47ad-b54c-d4d393c25059
=> feat: reorder steps on workflow card

source/javascripts/components/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/WorkflowCard/components/ChainedWorkflowCard.tsx, source/javascripts/components/WorkflowCard/components/StepList.tsx, source/javascripts/contexts/BitriseYmlProvider.tsx, source/javascripts/models/BitriseYmlService.spec.ts, source/javascripts/models/BitriseYmlService.ts, source/javascripts/pages/WorkflowsPage/WorkflowsPage.tsx
https://bitrise.atlassian.net/browse/CI-3311
https://github.com/user-attachments/assets/61accee5-2edc-430d-a54c-2baaecb4051b
=> feat: connect add step selector drawer to the new workflows page

source/javascripts/api/EnvVarsApi.ts
JIRA ticket: https://bitrise.atlassian.net/browse/CI-3382
Tech planning docs: https://bitrise.atlassian.net/wiki/spaces/RD/pages/3266969633/Loading+EnvVars+and+Secrets+in+WFE
=> feat: implement EnvVarsApi to load env vars from remote APIs

source/javascripts/components/StepCard/StepCard.tsx, source/javascripts/components/WorkflowCard/WorkflowCard.types.ts, source/javascripts/components/WorkflowCard/components/ChainedWorkflowCard.tsx, source/javascripts/components/WorkflowCard/components/ChainedWorkflowList.tsx, source/javascripts/components/WorkflowCard/components/SortableWorkflowsContext.tsx, source/javascripts/components/WorkflowCard/components/StepCard.tsx, source/javascripts/components/WorkflowCard/components/StepList.tsx
https://github.com/user-attachments/assets/1a1634e0-8c79-4a6d-96e1-62af036f7596
=> fix: step sorting drop animation

source/javascripts/pages/WorkflowsPage/components.new/StepDrawer/StepDrawer.tsx
https://bitrise.atlassian.net/browse/CI-3493
=> fix: clear filters after step drawer closes

rails/strings.rb, source/javascripts/_BitriseWorkflowEditor.js.erb, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/services/_requestService.js.erb
JIRA card: https://bitrise.atlassian.net/browse/BIVS-2776
=> [BIVS-2776] Manual build from WFE shows @user in the system

source/javascripts/controllers/_YMLController.js
JIRA card:  https://bitrise.atlassian.net/browse/BIVS-2806
=> [BIVS-2806] Fix configuration yaml dialog download button

source/javascripts/components/ConfigurationYmlSource/ConfigurationYmlSourceDialog.tsx, source/javascripts/components/UpdateConfigurationDialog/UpdateConfigurationDialog.tsx, source/javascripts/components/YmlEditorHeader/YmlEditorHeader.tsx, source/javascripts/hooks/useFeatureFlag.ts
https://bitrise.atlassian.net/browse/BIVS-2807
=> Clean up modular yml LD flag [BIVS-2807]

source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepSelectInput.tsx, source/javascripts/core/api/SecretApi.mswMocks.ts, source/javascripts/core/api/SecretApi.ts, spec/integration/test_bitrise.secrets.yml
closes https://bitrise.atlassian.net/browse/CI-3538
=> feat: create secret from InsertSecretPopover

source/javascripts/components/unified-editor/StepConfigDrawer/StepConfigDrawer.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/InsertEnvVarPopover/InsertEnvVarPopover.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/InsertSecretPopover/InsertSecretPopover.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/OutputVariablesTab.tsx, source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/AddStepButton.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/ChainedWorkflowCard.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/EnvVarsCard.tsx, source/javascripts/pages/WorkflowsPage/components.new/WorkflowCanvasPanel/WorkflowCanvasPanel.tsx
https://github.com/chakra-ui/chakra-ui/issues/8188#issuecomment-2331216028
=> fix: safari tooltip glitch

source/javascripts/components/unified-editor/WorkflowCard/components/ChainedWorkflowCard.tsx
https://github.com/user-attachments/assets/e21e4c6e-a845-4415-9f93-3e4a032f64e3
=> fix: missing visual feedback on chaining a chained workflow

source/javascripts/components/unified-editor/WorkflowConfig/components/EnvVarsCard.tsx, source/javascripts/core/api/BitriseYmlApi.ts
=> fix: Don't use YAML aliasing

package-lock.json, package.json, source/javascripts/pages/WorkflowsPage/components.new/DeleteWorkflowDialog/DeleteWorkflowDialog.tsx, source/javascripts/pages/WorkflowsPage/components/DeleteWorkflowDialog/DeleteWorkflowDialog.tsx
JIRA: https://bitrise.atlassian.net/browse/FRONTEND-486
=> [FRONTEND-486] Fix status icons

source/javascripts/components/unified-editor/StepBundle/StepBundleDrawer.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/PropertiesTab.tsx, source/javascripts/components/unified-editor/VersionChangedDialog/VersionChangedDialog.tsx, source/javascripts/components/unified-editor/WithGroup/WithGroupDrawer.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/StepCard.tsx, source/javascripts/core/api/StepApi.ts, source/javascripts/core/api/client.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/Step.ts, source/javascripts/core/models/StepService.spec.ts, source/javascripts/core/models/StepService.ts, source/javascripts/hooks/useAlgolia.ts, source/javascripts/hooks/useDefaultStepLibrary.ts, source/javascripts/hooks/useEnvVars.ts, source/javascripts/hooks/useStep.ts, spec/integration/test_bitrise.yml
Reverts bitrise-io/bitrise-workflow-editor#1209
=> Revert "feat: implement git:: step handling"

source/javascripts/components/unified-editor/WorkflowConfig/components/EnvVarsCard.tsx
=> fix: Validate WF env key uniqueness

source/javascripts/controllers/_WorkflowsController.js.erb
https://bitrise.atlassian.net/browse/CI-3759
=> fix: discard changes select another workflow

source/javascripts/components/unified-editor/StepSelectorDrawer/StepSelectorDrawer.utils.spec.ts, source/javascripts/components/unified-editor/StepSelectorDrawer/StepSelectorDrawer.utils.ts, source/javascripts/components/unified-editor/StepSelectorDrawer/hooks/useSearchSteps.ts
=> fix: Rank official step first in StepSelectorDrawer

.eslintrc.js, .storybook/main.ts, source/javascripts/core/models/BitriseYml.schema.ts, source/javascripts/pages/PipelinesPage/components/Toolbar/Toolbar.stories.tsx, source/javascripts/pages/PipelinesPage/components/Toolbar/Toolbar.tsx, source/javascripts/typings/globals.d.ts, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-3762
=> feat: floating toolbar for pipelines

.storybook/public/mockServiceWorker.js, package-lock.json, source/javascripts/components/UpdateConfigurationDialog/UpdateConfigurationDialog.tsx, source/javascripts/components/YmlEditorHeader/YmlEditorHeader.tsx, source/javascripts/pages/TriggersPage/components/LegacyTriggers/TriggerCard.tsx, source/javascripts/pages/TriggersPage/components/TargetBasedTriggers/AddTrigger.tsx, source/javascripts/pages/WorkflowsPage/components/WorkflowConfigPanel/components/TriggersTabPanel.tsx, source/javascripts/utils/segmentTracking.ts
JIRA: https://bitrise.atlassian.net/browse/BIVS-2835
=> [BIVS-2835] Target Based Triggers event tracking

source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/stores/BitriseYmlStore.ts
[CI-3774]
[CI-3774]: https://bitrise.atlassian.net/browse/CI-3774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Extend BitriseYML service with pipeline manipulation [CI-3774]

apiserver/api_server.go
so we overcome the network access warning when launching the server.
=> Local server should listen on localhost only

source/javascripts/_componentRegister.js, source/javascripts/components/EditableInput/EditableInput.stories.tsx, source/javascripts/components/EditableInput/EditableInput.tsx, source/javascripts/components/unified-editor/FloatingDrawer/FloatingDrawer.tsx, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_PipelinesController.js.erb, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/PipelineService.ts, source/javascripts/core/stores/BitriseYmlStore.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.store.tsx, source/javascripts/pages/PipelinesPage/PipelinesPage.stories.tsx, source/javascripts/pages/PipelinesPage/PipelinesPage.tsx, source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/components/PipelineConfigDrawer/PipelineConfigDrawer.tsx, source/javascripts/pages/PipelinesPage/components/Toolbar/Toolbar.tsx, source/javascripts/pages/PipelinesPage/hooks/useRenamePipeline.ts, source/templates/pipelines.slim, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-3780
=> feat: implement PipelineConfigDrawer

source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/PipelinesPage/components/Toolbar/Toolbar.tsx
[CI-3785]
[CI-3785]: https://bitrise.atlassian.net/browse/CI-3785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Show create pipeline button only if feature flag enabled [CI-3785]

source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.tsx
[CI-3784]
[CI-3784]: https://bitrise.atlassian.net/browse/CI-3784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Use graph specific empty pipelines page if applicable [CI-3784]

source/javascripts/components/EditableInput/EditableInput.tsx, source/javascripts/components/unified-editor/FloatingDrawer/FloatingDrawer.tsx, source/javascripts/core/models/PipelineService.ts, source/javascripts/core/models/WorkflowService.ts, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/WorkflowSelectorDrawer.stories.tsx, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/WorkflowSelectorDrawer.tsx, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/components/NoWorkflowsEmptyState.tsx, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/components/SearchResultEmptyState.tsx, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/components/SelectableWorkflowCard.tsx, source/javascripts/pages/PipelinesPage/components/WorkflowSelectorDrawer/components/WorkflowsList.tsx
https://bitrise.atlassian.net/browse/CI-3786
=> feat: workflow selector drawer

source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/stores/BitriseYmlStore.ts
[CI-3787]
[CI-3787]: https://bitrise.atlassian.net/browse/CI-3787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement addWorkflowToPipeline service method [CI-3787]

source/javascripts/pages/WorkflowsPage/WorkflowsPage.tsx
https://bitrise.atlassian.net/browse/CI-3806
=> fix: add step version

source/javascripts/components/unified-editor/WorkflowConfig/WorkflowConfigDrawer.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/PipelineConditionsCard.stories.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/PipelineConditionsCard.tsx, source/javascripts/components/unified-editor/WorkflowConfig/tabs/ConfigurationTab.tsx, source/javascripts/core/models/BitriseYml.schema.ts, source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/stores/BitriseYmlStore.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.store.tsx, source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx
[CI-3811]
[CI-3811]: https://bitrise.atlassian.net/browse/CI-3811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement Pipeline Conditions configuration section [CI-3811]

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/WorkflowNode.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/createGraphEdge.ts
https://bitrise.atlassian.net/browse/CI-3826
=> fix: layouting glitch when remove workflow from graph

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/GraphEdge.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/Handles.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/validateConnection.ts
https://bitrise.atlassian.net/browse/CI-3821
=> feat: connectable WorkflowNode right handle

source/javascripts/core/stores/BitriseYmlStore.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.tsx
https://bitrise.atlassian.net/browse/CI-3823
=> feat: apply graph connection

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/validateConnection.ts
https://bitrise.atlassian.net/browse/CI-3834
=> feat: validate connection

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/WorkflowNode.tsx
https://bitrise.atlassian.net/browse/CI-3848
=> fix: workflow node outline and border

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/GraphEdge.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/Handles.tsx
https://bitrise.atlassian.net/browse/CI-3849
=> fix: left handle color on connection snapped

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/WorkflowNode.tsx
https://bitrise.atlassian.net/browse/CI-3850
=> fix: workflow node hover style

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.const.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/GraphEdge.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/Handles.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode/WorkflowNode.tsx
https://bitrise.atlassian.net/browse/CI-3851
https://bitrise.atlassian.net/browse/CI-3854
=> feat: graph edge state styles

source/javascripts/controllers/_MainController.js.erb, source/javascripts/services/_appService.js.erb
=> fix: Disable header buttons on Secrets tab

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineCanvas.tsx
https://reactflow.dev/api-reference/components/minimap#making-the-mini-map-interactive
=> Make minimap pannable and zoomable

source/javascripts/components/unified-editor/StartBuildDialog/StartBuildDialog.stories.tsx, source/javascripts/components/unified-editor/StartBuildDialog/StartBuildDialog.tsx, source/javascripts/components/unified-editor/StartBuildDialog/useStartBuild.ts, source/javascripts/components/unified-editor/index.ts, source/javascripts/core/api/BuildApi.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.store.tsx, source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/components/Toolbar/Toolbar.tsx, source/javascripts/pages/WorkflowsPage/WorkflowsPage.tsx, source/javascripts/pages/WorkflowsPage/components/WorkflowMainToolbar.tsx, spec/integration/test_bitrise.yml
=> feat: Implement "Run pipeline" action

source/javascripts/components/unified-editor/WorkflowConfig/hooks/useRenameWorkflow.ts, source/javascripts/pages/PipelinesPage/hooks/useRenamePipeline.ts
https://bitrise.atlassian.net/browse/CI-3874
=> fix: workflow and pipeline renaming logic

source/javascripts/controllers/_MainController.js.erb, source/javascripts/pages/PipelinesPage/hooks/usePipelineSelector.ts, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-3858
=> feat: remember the last selected pipeline

source/javascripts/_componentRegister.js, source/javascripts/components/unified-editor/StepSelectorDrawer/StepSelectorDrawer.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/StepList.tsx, source/javascripts/pages/PipelinesPage/PipelinesPage.store.tsx, source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx, source/javascripts/pages/WorkflowsPage/WorkflowsPage.tsx
https://bitrise.atlassian.net/browse/CI-3891
=> feat: add step to workflows in graph pipelines

source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx
https://bitrise.atlassian.net/browse/CI-3894
https://bitrise.atlassian.net/browse/CI-3895
https://bitrise.atlassian.net/browse/CI-3933
=> feat: add clone, delete, and upgrade Steps on Pipelines page

source/javascripts/components/unified-editor/WorkflowConfig/WorkflowConfigPanel.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/WorkflowConfigHeader.tsx, source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/TriggersPage/components/LegacyTriggers/LegacyTriggers.tsx, source/javascripts/pages/TriggersPage/components/TriggersPage/TriggersPage.tsx
https://bitrise.atlassian.net/browse/BIVS-2893
=> Cleanup enable-target-based-triggers flag [BIVS-2893]

source/javascripts/components/unified-editor/CreateEntityDialog/CreateEntityDialog.stories.tsx, source/javascripts/components/unified-editor/CreateEntityDialog/CreateEntityDialog.tsx, source/javascripts/components/unified-editor/CreateWorkflowDialog/CreateWorkflowDialog.tsx, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.tsx
https://bitrise.atlassian.net/browse/FRONTEND-494
=> Unify create dialogs

package-lock.json, package.json, source/javascripts/components/YmlEditor/YmlEditor.tsx
https://bitrise.atlassian.net/browse/CI-3978
=> fix: bitrise.yml validation on Configuration YAML page

source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.tsx, source/javascripts/core/models/BitriseYml.schema.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/Workflow.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.stories.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.types.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/hooks/usePipelineWorkflows.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/createWorkflowNode.ts
https://bitrise.atlassian.net/browse/CI-3984
Storybook page: https://storybook.services.bitrise.dev/projects/wfe/pr-1356/?path=/story/javascripts-pages-pipelinespage--with-workflow-override
=> feat: pipeline workflow overrides

source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.types.ts, source/javascripts/components/unified-editor/WorkflowCard/components/ChainedWorkflowCard.tsx, source/javascripts/components/unified-editor/WorkflowConfig/WorkflowConfigDrawer.tsx, source/javascripts/components/unified-editor/WorkflowConfig/tabs/ConfigurationTab.tsx, source/javascripts/pages/PipelinesPage/PipelinesPage.store.tsx, source/javascripts/pages/PipelinesPage/components/Drawers/Drawers.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx, source/javascripts/pages/WorkflowsPage/WorkflowsPage.store.ts, source/javascripts/pages/WorkflowsPage/components/WorkflowCanvasPanel/WorkflowCanvasPanel.tsx
https://bitrise.atlassian.net/browse/CI-3999
=> feat: hide pipeline conditions of chained workflow

package-lock.json, package.json, source/javascripts/components/unified-editor/StepSelectorDrawer/components/AlgoliaStepList/AlgoliaStepList.tsx, source/javascripts/components/unified-editor/StepSelectorDrawer/components/AlgoliaStepList/components/AlgoliaStepListItems.tsx, source/javascripts/components/unified-editor/StepSelectorDrawer/components/AlgoliaStepList/hooks/useSearchAlgoliaSteps.ts, source/javascripts/components/unified-editor/StepSelectorDrawer/components/AlgoliaStepList/hooks/useVirtualItems.ts, source/javascripts/core/api/AlgoliaApi.ts, source/javascripts/core/api/StepApi.mswMocks.ts, source/javascripts/core/api/StepApi.ts, source/javascripts/core/models/StepService.ts
https://bitrise.atlassian.net/browse/CI-4081
=> feat: track selected steps in Algolia

source/javascripts/components/unified-editor/EntitySelector/EntitySelector.stories.tsx, source/javascripts/components/unified-editor/EntitySelector/EntitySelector.tsx, source/javascripts/pages/StepBundlesPage/components/StepBundlesSelector.tsx, source/javascripts/pages/WorkflowsPage/components/WorkflowSelector/WorkflowSelector.tsx
https://bitrise.atlassian.net/browse/BIVS-2915
=> Unify Workflow / Step bundle selector [BIVS-2915]

source/javascripts/controllers/_MainController.js.erb, source/javascripts/services/_appService.js.erb
=> feat: Request remote config and compare it with local baseline before saving

package-lock.json, package.json, source/javascripts/components/ConfigMergeDialog/ConfigMergeDialog.mocks.ts, source/javascripts/components/ConfigMergeDialog/ConfigMergeDialog.stories.tsx, source/javascripts/components/ConfigMergeDialog/ConfigMergeDialog.tsx
https://bitrise.atlassian.net/browse/CI-4149
=> feat: ConfigMergeDialog component

source/javascripts/core/models/PipelineService.ts, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.tsx
https://bitrise.atlassian.net/browse/CI-4166
=> fix: users can create graph pipeline based on staged

source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts
https://bitrise.atlassian.net/browse/CI-4167
=> feat: update workflow variant uses on workflow rename

source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInputGroup.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepSelectInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/ConfigurationTab.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/PropertiesTab.tsx, source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/StepService.spec.ts, source/javascripts/core/models/StepService.ts, source/javascripts/core/stores/BitriseYmlStore.ts
=> feat: Allow users to reset inputs back to their default value via the UI

source/javascripts/components/unified-editor/StepConfigDrawer/components/StepCodeEditor.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInputGroup.tsx, source/javascripts/core/models/StepService.spec.ts, source/javascripts/core/models/StepService.ts
https://bitrise.atlassian.net/browse/CI-4175
=> fix: script step default content

source/javascripts/controllers/_EnvVarsController.js.erb, source/javascripts/controllers/_LicensesController.js, source/javascripts/controllers/_MainController.js.erb, source/javascripts/controllers/_PipelinesController.js.erb, source/javascripts/controllers/_StackController.js.erb, source/javascripts/controllers/_StepBundlesController.js, source/javascripts/controllers/_TriggersController.js, source/javascripts/controllers/_WorkflowsController.js.erb, source/javascripts/controllers/_YMLController.js, source/templates/licenses.slim, source/templates/step_bundles.slim, source/templates/triggers.slim, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-4177
=> fix: state inconsistency

source/javascripts/controllers/_MainController.js.erb, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-4210
=> feat: save merged yaml with cmd/ctrl+s command

source/javascripts/services/_appService.js.erb
[incident-2025-01-28-unable-to-change-stack-in-wfe-1363](https://bitfall.slack.com/archives/C08AZMMUC9X)
=> fix: incident-2025-01-28-unable-to-change-stack-in-wfe-1363

source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInputGroup.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/ConfigurationTab.tsx, source/javascripts/core/models/StepVariableService.ts, spec/integration/test_bitrise.yml
=> [SSW-2075] Fix user defined values are not loaded into input fields

source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.stories.tsx, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.tsx
https://bitrise.atlassian.net/browse/CI-4224
=> feat: list staged pipelines in the create pipeline dialog based on selector

source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/PipelineService.spec.ts, source/javascripts/core/models/PipelineService.ts
[CI-4225](https://bitrise.atlassian.net/browse/CI-4225)
[CI-4225]: https://bitrise.atlassian.net/browse/CI-4225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: create an empty pipeline based on a staged pipeline

source/javascripts/controllers/_MainController.js.erb
https://bitrise.atlassian.net/browse/CI-4230
=> feat: add "Workflow Editor Config Merge Popup Save Results Button Clicked" event

source/javascripts/components/ConfigMergeDialog/ConfigMergeDialog.tsx, source/javascripts/controllers/_MainController.js.erb
https://bitrise.atlassian.net/browse/CI-4231
=> feat: add "Workflow Editor Config Merge Popup Dismissed" event

source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/core/models/BitriseYmlService.ts, source/javascripts/core/models/PipelineService.spec.ts, source/javascripts/core/models/PipelineService.ts
https://bitrise.atlassian.net/browse/CI-4226
=> feat: convert workflow references with depends_on

source/javascripts/controllers/_MainController.js.erb
https://bitrise.atlassian.net/browse/CI-4238
=> fix: improve hash change synchronization between iframe and parent window

source/javascripts/core/models/PipelineService.spec.ts, source/javascripts/core/models/PipelineService.ts, source/javascripts/hooks/useBitriseYmlStore.ts, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/hooks/usePipelineConversionNotification.ts, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-4228
=> feat: display pipeline conversion notification if needed

source/javascripts/controllers/_MainController.js.erb, source/javascripts/services/_appService.js.erb, source/javascripts/services/_requestService.js.erb, source/javascripts/services/request-service.ts, spec/javascripts/requestService.spec.js
https://bitrise.atlassian.net/browse/CI-4286
=> feat: receive and store X-Bitrise-Config-Version header

source/javascripts/services/_appService.js.erb, source/javascripts/services/_requestService.js.erb, source/javascripts/services/request-service.ts, spec/javascripts/requestService.spec.js
https://bitrise.atlassian.net/browse/CI-4287
=> feat: send X-Bitrise-Config-Version header on save

source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/services/_appService.js.erb
https://bitrise.atlassian.net/browse/CI-4307
=> feat: use feature flag for X-Bitrise-Config-Version header sending

source/javascripts/core/models/PipelineService.spec.ts, source/javascripts/core/models/PipelineService.ts, spec/integration/test_bitrise.yml
https://bitrise.atlassian.net/browse/CI-4308
=> fix: convert stages to graph dependency duplications

source/javascripts/components/unified-editor/StepBundlesConfig/StepBundleConfigDrawer.tsx, source/javascripts/components/unified-editor/StepSelectorDrawer/StepSelectorDrawer.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/AddStepButton.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/StepCard.tsx, source/javascripts/components/unified-editor/WorkflowCard/components/StepListItem.tsx, source/javascripts/controllers/_MainController.js.erb
JIRA: https://bitrise.atlassian.net/browse/BIVS-2975
=> Cleanup Launch Darkly flag for Step bundles

source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.tsx, source/javascripts/core/models/BitriseYml.schema.ts, source/javascripts/core/models/Workflow.ts, source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.stories.tsx, source/javascripts/pages/PipelinesPage/PipelinesPage.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.const.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/GraphPipelineCanvas.types.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/hooks/usePipelineWorkflows.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/utils/createWorkflowNode.ts, spec/integration/test_bitrise.yml, webpack.config.js
https://bitrise.atlassian.net/browse/CI-4331
Related story: https://storybook.services.bitrise.dev/projects/wfe/pr-1438/?path=/story/javascripts-pages-pipelinespage--with-parallel-workflow
=> feat: display parallelism on workflow cards

source/javascripts/components/unified-editor/WorkflowConfig/components/GitStatusNameInput.tsx, source/javascripts/components/unified-editor/WorkflowConfig/tabs/PropertiesTab.tsx, source/javascripts/core/models/BitriseYmlService.spec.ts, source/javascripts/pages/PipelinesPage/components/PipelineConfigDrawer/tabs/PropertiesTab.tsx
https://bitrise.atlassian.net/browse/BIVS-2991
=> Add git status name input to pipelines [BIVS-2991]

source/javascripts/components/unified-editor/StepSelectorDrawer/components/AlgoliaStepList/hooks/useCalculateColumns.ts, source/javascripts/hooks/useIsTruncated.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx
https://app.datadoghq.com/error-tracking/issue/dc294514-954c-11ef-a801-da7ad0900002
=> fix: ResizeObserver loop completed with undelivered notifications

package-lock.json, package.json, source/javascripts/hooks/useFeatureFlag.ts
https://bitrise.atlassian.net/browse/CI-4385
=> feat: re-introduce Launchdarkly SDK

source/javascripts/components/unified-editor/WorkflowConfig/components/PipelineConditionsCard.tsx, source/javascripts/core/services/GraphPipelineWorkflowService.spec.ts, source/javascripts/core/services/GraphPipelineWorkflowService.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.stories.tsx
JIRA task: https://bitrise.atlassian.net/browse/CI-4426
Related story: https://storybook.services.bitrise.dev/projects/wfe/pr-1479/?path=/story/javascripts-pages-pipelinespage--with-parallel-workflow-collision
=> feat: validate parallel collisions on UI

source/javascripts/_componentRegister.js, source/javascripts/controllers/_EnvVarsController.js, source/javascripts/pages/index.ts, source/stylesheets/_index.css, source/templates/env_vars.html
https://bitrise.atlassian.net/browse/CI-4438
=> feat: add EnvVarsPage to env_vars.html

source/javascripts/components/unified-editor/WorkflowConfig/components/StackAndMachineCard.tsx, source/javascripts/core/services/MachineTypeService.ts, source/javascripts/core/services/StackAndMachineService.spec.ts, source/javascripts/core/services/StackAndMachineService.ts, source/javascripts/core/services/StackService.ts
Avoid saving macOS machine to Linux stack and non-macOS machine to xCode stack
=> fix: save valid stack and machine type combination to yml

source/javascripts/core/services/PipelineService.ts, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineCanvas.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineConversionNotification.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/PipelineConversionSignposting.tsx, source/javascripts/pages/PipelinesPage/hooks/usePipelineConversionSignposting.ts
https://bitrise.atlassian.net/browse/CI-4449
=> feat: pipeline conversion signposting

source/javascripts/components/unified-editor/WorkflowConfig/components/PipelineConditionsCard.tsx, source/javascripts/core/services/GraphPipelineWorkflowService.spec.ts, source/javascripts/core/services/GraphPipelineWorkflowService.ts
https://bitrise.atlassian.net/browse/CI-4463
=> feat: remove Env Var related copies around parallel input

source/javascripts/components/unified-editor/WorkflowCard/WorkflowCard.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/PipelineConditionsCard.tsx, source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/PipelinesPage/PipelinesPage.stories.tsx, source/javascripts/pages/PipelinesPage/components/PipelineCanvas/GraphPipelineCanvas/components/WorkflowNode.tsx
https://bitrise.atlassian.net/browse/CI-4465
=> feat: cleanup the parallel feature flag

package-lock.json, source/javascripts/components/unified-editor/CreateEntityDialog/CreateEntityDialog.stories.tsx, source/javascripts/components/unified-editor/CreateEntityDialog/CreateEntityDialog.tsx, source/javascripts/components/unified-editor/CreateStepBundleDialog/CreateStepBundleDialog.tsx, source/javascripts/components/unified-editor/CreateWorkflowDialog/CreateWorkflowDialog.tsx, source/javascripts/core/services/BitriseYmlService.spec.ts, source/javascripts/core/services/BitriseYmlService.ts, source/javascripts/core/stores/BitriseYmlStore.ts, source/javascripts/pages/PipelinesPage/components/CreatePipelineDialog/CreatePipelineDialog.tsx, source/javascripts/pages/StepBundlesPage/components/Drawers.tsx
https://bitrise.atlassian.net/browse/BIVS-3040
=> Create step bundle based on utility workflow [BIVS-3040]

source/javascripts/components/unified-editor/PriorityInput/PriorityInput.tsx
https://bitrise.atlassian.net/browse/BIVS-3045
=> Add devcenter link to priority input [BIVS-3045]

source/javascripts/components/_Workflow.js
https://app.datadoghq.com/error-tracking?query=-error.handling%3Ahandled&et-side=activity&issueId=02b5a74a-ed2c-11ef-a38f-da7ad0900002&source=browser&utm_event=event.case.status_changed&utm_medium=email&utm_source=cm_standard
JIRA Ticket: https://bitrise.atlassian.net/browse/FRONTEND-506
=> feat: handle this.machineType(...) is null errors gracefully

package-lock.json, package.json, webpack.config.js
https://bitrise.atlassian.net/browse/FRONTEND-517
=>  feat: add subresource-integrity-plugin to make DataDog errors meaningful

source/javascripts/pages/YmlPage/YmlPage.tsx, source/javascripts/pages/YmlPage/components/YmlEditorHeader.tsx, source/stylesheets/_index.css
https://bitrise.atlassian.net/browse/BIVS-3056
=> Refact notifications on Configuration YAML page [BIVS-3056]

source/javascripts/components/StacksAndMachine/DefaultStackAndMachine.tsx, source/javascripts/components/StacksAndMachine/MachineTypeSelector.tsx, source/javascripts/components/StacksAndMachine/StackAndMachine.tsx, source/javascripts/components/StacksAndMachine/WorkflowStackAndMachine.tsx, source/javascripts/core/services/BitriseYmlService.spec.ts, source/javascripts/core/services/BitriseYmlService.ts, source/javascripts/core/services/StackAndMachineService.ts, source/javascripts/core/stores/BitriseYmlStore.ts, source/javascripts/hooks/useDefaultStackAndMachine.ts, source/javascripts/pages/StacksAndMachinesPage/StacksAndMachinesPage.stories.tsx, source/javascripts/pages/StacksAndMachinesPage/tabs/WorkflowsTab.tsx
JIRA-ticket: https://bitrise.atlassian.net/browse/CI-4535
=> [CI-4535] Update the selected default stack and machine in YML

source/javascripts/components/StacksAndMachine/DefaultStackAndMachine.tsx, source/javascripts/components/StacksAndMachine/StackAndMachine.tsx, source/javascripts/components/StacksAndMachine/StackSelector.tsx, source/javascripts/components/StacksAndMachine/WorkflowStackAndMachine.tsx, source/javascripts/core/api/StacksAndMachinesApi.mswMocks.ts, source/javascripts/core/models/Stack.ts, source/javascripts/core/services/BitriseYmlService.ts, source/javascripts/core/services/StackAndMachineService.ts, source/javascripts/hooks/useDefaultStackAndMachine.ts, source/javascripts/pages/StacksAndMachinesPage/StacksAndMachinesPage.stories.tsx, source/javascripts/pages/StacksAndMachinesPage/StacksAndMachinesPage.tsx, source/javascripts/typings/globals.d.ts
https://bitrise.atlassian.net/browse/CI-4537
=> Implement the "Use previous stack version" logic [CI-4537]

source/javascripts/hooks/useSelectedWorkflow.ts
JIRA ticket: https://bitrise.atlassian.net/browse/CI-4736
=> fix(quick): handle generated workflow ID selection

source/javascripts/components/StacksAndMachine/StackAndMachine.tsx, source/javascripts/components/StacksAndMachine/StackAndMachineWrapper.tsx, source/javascripts/components/unified-editor/WorkflowConfig/components/StackAndMachineCard.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3124
=> [BIVS-3124] Use new Stack and Machine component in Workflow drawer/panel

package-lock.json, source/javascripts/components/unified-editor/Triggers/components/AddTrigger/AddTrigger.tsx
https://bitrise.atlassian.net/browse/BIVS-3135
And fix this: https://github.com/bitrise-io/bitrise-workflow-editor/security/dependabot/202
=> Fix typo [BIVS-3135]

source/javascripts/controllers/_MainController.js, source/javascripts/datadog-rum.js
https://bitrise.atlassian.net/browse/CI-4807
=> feat: DataDog track views manually

source/javascripts/components/_Workflow.js, source/javascripts/controllers/_MainController.js, source/javascripts/controllers/_StackController.js, source/javascripts/datadog-rum.js, source/javascripts/typings/globals.d.ts, source/javascripts/utils/datadogCustomRumTiming.ts, webpack.config.js
related to: https://bitrise.atlassian.net/browse/CI-4807
=> fix: DataDog initialization

source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInputGroup.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/tabs/ConfigurationTab.tsx, source/javascripts/core/services/StepVariableService.test.ts, source/javascripts/core/services/StepVariableService.ts
=> fix: StepInputGroup can get null inputs

source/javascripts/core/models/BitriseYml.ts, source/javascripts/core/models/Step.ts, source/javascripts/core/services/BitriseYmlService.spec.ts, source/javascripts/core/services/BitriseYmlService.ts, source/javascripts/core/services/StepService.ts, source/javascripts/hooks/useStep.ts, spec/integration/test_bitrise.yml
Ensure the code correctly manages cases where step items may be null in the YAML configuration, improving robustness and preventing potential errors.
=> Fix handling of null step items in YAML

source/javascripts/components/unified-editor/Triggers/Triggers.utils.ts, source/javascripts/pages/TriggersPage/components/TargetBasedTriggers/TargetBasedTriggers.tsx
https://bitrise.atlassian.net/browse/BIVS-3194
=> Trigger fixes [BIVS-3194]

source/javascripts/core/utils/MonacoUtils.ts
https://bitrise.atlassian.net/browse/CI-4987
=> fix: completion provider abort error

source/javascripts/core/api/client.ts
https://app.datadoghq.com/error-tracking/issue/74dab0e0-2a76-11f0-a4ae-da7ad0900002
=> fix: add abort error message in API client raw function

source/javascripts/components/DiffEditor/DiffEditor.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3292
=> Show revert changes button in WFE's diff editor

source/javascripts/components/unified-editor/StepBundleConfig/StepBundleConfigInputs.tsx, source/javascripts/components/unified-editor/StepBundleConfig/StepBundleInputs/StepBundleInputsDialog.tsx, source/javascripts/components/unified-editor/StepBundleConfig/StepBundleInputs/StepBundleInputsForm.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3287
=> [BIVS-3287] Move Step bundle inputs into a dialog

source/javascripts/components/unified-editor/StepBundleConfig/StepBundleConfig.context.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3314
=> [BIVS-3314] Datadog: TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

source/javascripts/components/unified-editor/WhenToRunCard/WhenToRunCard.tsx, source/javascripts/pages/StepBundlesPage/StepBundlesPage.stories.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3323
=> [BIVS-3323] Hide always_run functionality from WF page and Step bundles page

source/javascripts/components/unified-editor/StepBundleConfig/StepBundleConfigurationTab.tsx, source/javascripts/hooks/useFeatureFlag.ts, source/javascripts/pages/StepBundlesPage/StepBundlesPage.stories.tsx, source/javascripts/pages/WorkflowsPage/WorkflowsPage.stories.tsx
JIRA: https://bitrise.atlassian.net/browse/BIVS-3325
=> Removed enable-wfe-step-bundles-when-to-run featureFlag

source/javascripts/components/AutoGrowableInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepInput.tsx, source/javascripts/components/unified-editor/StepConfigDrawer/components/StepSelectInput.tsx
=> fix: step input buttongroup visibility

source/javascripts/components/LazyRoute.tsx, source/javascripts/core/api/BitriseYmlApi.ts, source/javascripts/hooks/useCiConfig.ts, source/javascripts/main.tsx
https://bitrise.atlassian.net/browse/CI-5389
=> [CI-5389] Add skipValidation prop to getCiConfig

source/javascripts/core/utils/YmlUtils.spec.ts, source/javascripts/core/utils/YmlUtils.ts
https://bitrise.atlassian.net/browse/FRONTEND-551
=> fix: FRONTEND-551
